[project]
name = "dns"
version = "0.1.0"
description = "Declarative DNS management with OctoDNS"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "octodns==1.13.0",
    "octodns-digitalocean==1.0.0",
    "octodns-ovh==1.1.0",
]
