---

name: OctoDNS apply
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths:
      - 'zones/**/*.yaml'
      - octodns.yaml
      - requirements.txt
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - uses: solvaholic/octodns-sync@c7fd61b8e988b56687199aeb2c711601f4b1e1c1
        with:
          config_path: octodns.yaml
          doit: --doit
        env:
          DO_TOKEN: ${{ secrets.do_token }}
          OVH_APPLICATION_KEY: ${{ secrets.ovh_application_key }}
          OVH_APPLICATION_SECRET: ${{ secrets.ovh_application_secret }}
          OVH_CONSUMER_KEY: ${{ secrets.ovh_consumer_key }}
