---

name: Lint YAML & Makefile
# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**/*.yaml'
      - Makefile
jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: frenck/action-yamllint@v1
  lint-makefile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check that targets compile
        run: make -n
