---

name: Lint Makefile
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - Makefile
jobs:
  lint-makefile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check that targets compile
        run: make -n
