---

name: OctoDNS plan
# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'zones/**/*'
      - octodns.yaml
      - requirements.txt
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
      - run: pip install -r requirements.txt
      - uses: solvaholic/octodns-sync@c7fd61b8e988b56687199aeb2c711601f4b1e1c1
        with:
          config_path: octodns.yaml
          add_pr_comment: 'Yes'
          pr_comment_token: ${{ github.token }}
        env:
          DO_TOKEN: ${{ secrets.do_token }}
          OVH_APPLICATION_KEY: ${{ secrets.ovh_application_key }}
          OVH_APPLICATION_SECRET: ${{ secrets.ovh_application_secret }}
          OVH_CONSUMER_KEY: ${{ secrets.ovh_consumer_key }}
