---

name: OctoDNS plan
# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'zones/**/*'
      - octodns.yaml
      - requirements.txt
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.8"
          enable-cache: true
      - name: Get dependencies
        run: |
          uv venv .venv
          UV_PROJECT_ENVIRONMENT='.venv' uv sync
          echo "${PWD}/.venv/bin" >> "$GITHUB_PATH"
      - uses: solvaholic/octodns-sync@v3.1.1
        with:
          config_path: octodns.yaml
          add_pr_comment: 'Yes'
          pr_comment_token: ${{ github.token }}
        env:
          DO_TOKEN: ${{ secrets.do_token }}
          OVH_APPLICATION_KEY: ${{ secrets.ovh_application_key }}
          OVH_APPLICATION_SECRET: ${{ secrets.ovh_application_secret }}
          OVH_CONSUMER_KEY: ${{ secrets.ovh_consumer_key }}
